version: '3.7'

services:
  app:
    container_name: pmbonline_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - laravel

networks:
  laravel:
    driver: bridge